
trigger: 
  branches:
    include:
      - develop
      - main
      - feature/*

pr:
  branches:
    include:
    - features/*

# pool: selfhostagent

# parameters:
#   - 


stages:

# - stage: SoftwareComponentCompositionAnalysis
#   displayName: Software Composition Analysis
#   jobs:
#   - job: securityvulnerabilityscan
#     displayName: security scan (Retire.js)

#     steps:
#     - task: PowerShell@2
#       displayName: security scan (Retire.js)
#       inputs:
#         targetType: 'inline'
#         script: |
#           npm install -g retire
#           retire
#           retire --exitwith 0


# - stage: StaticCodeAnalysis
#   displayName: Static Code Analysis
#   jobs: 
#   - job: SonarQubeAnalysis
#     displayName: Static Code Analysis (SonarQube)
#     steps:
#     - task: PowerShell@2
#       inputs:
#         targetType: 'inline'
#         script: 'sonar -D sonar.host.url=https://sonarqube.devopsinsiders.com/ -D sonar.token=$(SONAR_TOKEN) -D sonar.projectKey=todo-ui-frontend'


# - stage: CodeQualityCheck
#   displayName: Code Quality and Linting
#   dependsOn: SoftwareComponentCompositionAnalysis
#   jobs:
#   - job: LintingCheck
#     displayName: Linting Check

#     steps: 

    # - task: PowerShell@2
    #   displayName: JavaScript Lint (Biome)
    #   continueOnError: true
    #   inputs:
    #     targetType: 'inline'
    #     script: |
    #       Invoke-WebRequest -Uri "https://github.com/biomejs/biome/releases/download/%40biomejs%2Fbiome%402.3.11/biome-win32-x64.exe" -OutFile "$(Agent.ToolsDirectory)/biome.exe"
    #       $(Agent.ToolsDirectory)/biome.exe lint $(System.DefaultWorkingDirectory)/src/

    # - task: NodeTool@0
    #   displayName: 'Install Node.js'
    #   inputs:
    #     versionSource: 'spec'
    #     versionSpec: '24.x'
    #     checkLatest: true

    # - task: CmdLine@2
    #   displayName: 'Install npm dependencies'
    #   inputs:
    #     script: 'npm install'


    # - task: PowerShell@2
    #   displayName: create file stylelint.config.mjs
    #   inputs:
    #     targetType: 'inline'
    #     script: |
    #       if (-Not (Test-Path "stylelint.config.mjs")) {
          
    #               $lines = @(
    #                 "/** @type {import('stylelint').Config} */",
    #                 "export default {",
    #                 "  extends: [""stylelint-config-standard""]",
    #                 "};"
    #               )
          
    #               $lines | Out-File -FilePath stylelint.config.mjs -Encoding UTF8
    #             }
    #             else {
    #               Write-Host "stylelint.config.mjs already exists, skipping creation"
    #             }


    # - task: PowerShell@2
    #   continueOnError: true
    #   displayName: CSS Linting (Stylelint)
    #   inputs:
    #     targetType: 'inline'
    #     script: |
          
    #       npm add -D stylelint stylelint-config-standard
    #       npx stylelint "**/*.css"

          
          # npm create stylelint@latest
          
          # npm install -g stylelint
          # npm install -g stylelint-config-standard        
          # stylelint $(System.DefaultWorkingDirectory)/src --config stylelint.config.mjs

    # - task: PowerShell@2
    #   continueOnError: true
    #   displayName: YAML Linting (yamllint)    
    #   inputs:
    #     targetType: 'inline'
    #     script: |
    #       pip install --user yamllint
    #       yamllint $(System.DefaultWorkingDirectory)

    # - task: PowerShell@2
    #   continueOnError: true
    #   displayName: Markdown Linting (markdownlint)      
    #   inputs:
    #     targetType: 'inline'
    #     script: |
    #       npm install -g markdownlint-cli      
    #       markdownlint $(System.DefaultWorkingDirectory)/




# - stage: BuildAndPackage
#   displayName: Build & Artifact Packaging
#   jobs:
#   - job: ApplicationBuild
#     displayName: Application Build
#     steps:

#     - task: NodeTool@0
#       displayName: Install Node.js
#       inputs:
#         versionSource: 'spec'
#         versionSpec: '16.x'

#     - task: PowerShell@2
#       displayName: Install dependency npm
#       inputs:
#         targetType: 'inline'
#         script: 'npm install'
#     - task: PowerShell@2
#       displayName: Application Build
#       inputs:
#         targetType: 'inline'
#         script: 'npm run build'

#     - task: PublishPipelineArtifact@1
#       displayName: Publish Build Artifact
#       inputs:
#         targetPath: '$(System.DefaultWorkingDirectory)/build/'
#         artifact: 'todo-frontend-ui'
#         publishLocation: 'pipeline'



- stage: deployToDev
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
  displayName: Deploy To Dev VM
  jobs:
  # - job: deployToDEVonVMSSH
  #   displayName: Deploy To Dev VM ssh
  #   steps:
    # - task: DownloadPipelineArtifact@2
    #   displayName: Download Build Artifact
    #   inputs:
    #     buildType: 'specific'
    #     project: 'e161fa95-0015-4b95-8e1b-439d8e5ff69e'
    #     definition: '12'
    #     buildVersionToDownload: 'specific'
    #     pipelineId: '172'
    #     artifactName: 'todo-frontend-ui'
    #     targetPath: '$(System.DefaultWorkingDirectory)/build_artifacts'

    # - task: DownloadPipelineArtifact@2
    #   displayName: Download Build Artifact
    #   inputs:
    #     buildType: 'current'
    #     artifactName: 'todo-frontend-ui'
    #     targetPath: '$(System.DefaultWorkingDirectory)/build_artifacts'

    # - task: CopyFilesOverSSH@0
    #   inputs:
    #     sshEndpoint: 'ssh serv conn- frontend vm'
    #     sourceFolder: '$(System.DefaultWorkingDirectory)/build_artifacts/'
    #     contents: '**'
    #     cleanTargetFolder: true
    #     targetFolder: '/home/ashuvm'
    #     readyTimeout: '20000'

    # - task: SSH@0
    #   displayName: install nginx
    #   inputs:
    #     sshEndpoint: 'ssh serv conn- frontend vm'
    #     runOptions: 'inline'
    #     inline: |
    #       #!/bin/bash
    #       set +e
    #       export DEBIAN_FRONTEND=noninteractive

    #       sudo apt-get update -y
    #       sudo apt-get install -y nginx

    #       sudo systemctl restart nginx
    #       exit 0

    #     readyTimeout: '20000'

    # - task: SSH@0
    #   displayName: build copy to var/www/html
    #   inputs:
    #     sshEndpoint: 'ssh serv conn- frontend vm'
    #     runOptions: 'inline'
    #     inline: |
    #       sudo rm -rf /var/www/html/*
    #       sudo cp -r /home/ashuvm/* /var/www/html
    #     readyTimeout: '20000'




  - deployment: deployToDEVonVMEnvironment
    displayName: Deploy To Dev VM Environment
    environment:
     name: Dev-Todo-UI
    #  resourceId: 
    #  resourceName: 
     resourceType: VirtualMachine
    #  tags: 
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            displayName: Download Build Artifact
            inputs:
              buildType: 'specific'
              project: 'e161fa95-0015-4b95-8e1b-439d8e5ff69e'
              definition: '12'
              buildVersionToDownload: 'specific'
              pipelineId: '172'
              artifactName: 'todo-frontend-ui'
              targetPath: '$(System.DefaultWorkingDirectory)/build_artifacts'           



          - task: Bash@3
            displayName: Install Nginx
            inputs:
              targetType: 'inline'
              script: |
                #!/bin/bash
                set +e
                export DEBIAN_FRONTEND=noninteractive
                
                sudo apt-get update -y
                sudo apt-get install -y nginx
                
                sudo systemctl restart nginx
                exit 0

          - task: Bash@3
            displayName: copy Build Artifact to nginx
            inputs:
              targetType: 'inline'
              script: |
                sudo rm -rf /var/www/html/*
                sudo cp -r $(System.DefaultWorkingDirectory)/build_artifacts/* /var/www/html
